
CREATE TABLE IMP_REPORT_STATUS_TRACKING (
    REPORT_ID NUMBER NOT NULL,
    ALERT_ID VARCHAR2(50) NOT NULL,
    UPDATE_DATE DATE,
    TECH_COMMENT VARCHAR2(100),
    BUSINESS_COMMENT VARCHAR2(100)
);
