CREATE TABLE "IMP_REPORT_LOG"
   (  "REPORT_ID" NUMBER(30,0) NOT NULL ENABLE,
      "ALERT_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
      "REPORT_DATE_ORIG" DATE,
      "REPORT_DATE_UPDATED" DATE,
      "FIRST_RESPONSE_ORIG" CHAR(1 CHAR),
      "FINAL_RESPONSE_VALID" CHAR(1 CHAR),
      "RECEIVED_DATE" DATE,
      "MISPAR_TKINA" NUMBER(30,0),
      "SAR_FOLDER_NAME" VARCHAR2(500 CHAR),
      "STATUS_DESC" VARCHAR2(30 CHAR),
      "ALERT_ATTACHMENTS" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ALTER TABLE "IMP_REPORT_LOG" MODIFY ("REPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "IMP_REPORT_LOG" MODIFY ("ALERT_ID" NOT NULL ENABLE);